### ISSUE TITLE
Installer fails in Ubuntu 14.04.3

### ISSUE THREAD

**Issue by IamMrE** [Nanolx/bashstyle-ng#1]
Software Center opens the .deb pkg and reports "Dependency is not satisfiable: python3-configobj.

Checked python version:
😎  ------------------------------------------------------------------------- 10:21 PM
Ubu-MacPro-Dt:[imattux] ~ $ python3 -V
Python 3.4.0
😎  ------------------------------------------------------------------------- 10:21 PM
Ubu-MacPro-Dt:[imattux] ~ $ 

I'm a noob and as you can see, I'm interested in  tweaking my PS1. Pls lmk if there's some obvious thing I'm missing. Thx!

**Comment by Nanolx** [comment]
It may be that there's no python3-configobj package is available in Ubuntu 14.04. 

You  may try downloading and installing the package from Debian GNU/Linux: https://packages.debian.org/sid/python3-configobj

**Comment by IamMrE** [comment]
That did the trick, Chris - Thanks for the super speedy reply! 

If you want a suggestion, the thing I'm working on is a prompt that indicates the exit code of the previous command (green sunglass emoji and separator fill if  \$?=0; else red frown emoji, exit code, red separator fill). 

Not that I'm asking you to do that for me but that's what I'm working on and I didn't see that you have anything related to \$? and maybe other (noobs?) are interested in exit codes. 

Thanks again,

Matt

**Comment by Nanolx** [comment]
That's already implemented in the upcoming version 9.1.

* ${lastexit}: exit code for last command
* ${lastcommand}: last command and arguments (full length)
* ${lastcommandprintable}: last command and arguments (cut at 21th character, for better prompt integration)

completion, PROMPT_COMMAND, trap and echo'ing those variables will NOT change those values. The Equinox prompt style (called "Clock Advanced" in version 9.0) already included that. It will show:

* ( ✔: some command )─┤   -- for a successfully executed command in green
* ( ✘: some command )─┤   -- for a non-successfully executed command in red

Also the Custom Prompt Builder in version 9.1 is much better than before and as of today includes those three new variables. You can check it out from the git repo or  wait until ~3rd of October for the official release. In case you check out from git, be sure to read the NEWS file, it lists everything that's new in more readable from than 'git log'.

**Comment by IamMrE** [comment]
That's pretty funny. I worked on it all day and have bash working almost perfectly on the Linux side (now I'm trying to get the Mac side looking exactly the same...) The point of all this for me was to learn what's going on under the hood and stop relying on great people like you to build GUI tools for people like me. I did use your tools to give me some examples, but I actually ended up hacking/patching together 3 different people's bashrc files by hand to make the one that I'm happy with. I've got a better handle on if/then/else, escape codes and all those pesky brackets, curly braces, and quotes now and that's a good thing. ;-) 

I did have a problem with bashstyle, however. I went into it a few times and looked at the code for various options, but I never had it replace my PS1. I'd opened and closed it a few times without any trouble, and then when I opened it again, the main window was pushed all the way up to the top of my screen. I couldn't close it, move it or hide it. I closed all other apps and windows - there were quite a few terminal windows and a few Firefox windows as well. It was finally the only window left on screen. It was functional, but I couldn't move, hide or close it. I logged out, logged back in, started it with nothing else running and it was still stuck at the top of my screen. I purged with apt-get and manually removed a bunch of config files. I figure between 12-15 windows and with Gnome and Compiz and Unity all fighting for control, something got whacked. 

You needn't do anything on my behalf, I'm fine. If, on the other hand, you're concerned about this issue, I'd be happy to work with you to try to recreate it and track down the culprit. I'm sure I'd learn something if you care to take a look. And at the same time, getting anything to work on every permutation of Linux has to be impossible and I wouldn't blame you for not worrying about it.

Thanks for everything. Judging from the number of people asking for help with colors, prompts, etc;  the relative scarcity of good, current answers and the fact that it far from easy for a noob to write this stuff by hand, I think you have either a great gift to the community or maybe even a tool you could get some money for. Cheers ;-)

**Comment by Nanolx** [comment]
Hmm... some distributions have a PS1 in ~/.bashrc, some only set it in /etc/bashrc. I just changed the start up mechanism of BashStyle-NG to prevent PS1 from ~/.bashrc from overriding PS1 from BashStyle-NG. It should work now properly

And thanks for your kind words. :)
