### ISSUE TITLE
After removing the debian package, error on new bash session.

### ISSUE THREAD

**Issue by alexfornuto** [Nanolx/bashstyle-ng#2]
Running Debian 7.9, bashstyle-ng wasn't working correctly for me. That's fine, I didn't feel like debugging it properly. I installed it from the .deb file, so I remove it with `apt-get remove bashstyle-ng`.

Now every new bash session I start has:

```
bash: /usr/share/bashstyle-ng/rc/nx-rc: No such file or directory
```

This is a minor annoyance, but I'd like to remove it. I checked the obvious place (.bashrc) and did some googling for the error message, with no resulted (quoted).

**Comment by Nanolx** [comment]
What version did you use? You may want to try with the GIT version, as I made a few changes to the start up mechanism, so it should now work in all cases. Though it's built on Debian, so should work there out of the box.

Either way: you may want to check ~/.bashrc or /etc/bash.bashrc for bashstyle-ng related entries and remove them.

**Comment by Nanolx** [comment]
I'm closing this now. If there are still issues, feel free to re-open, but I assume everything's fine now.

**Comment by alexfornuto** [comment]
It was `/etc/bash.bashrc`, thanks.
