### ISSUE TITLE
Should shopt/nanoopt/vimopt/whateverOPT names be translatable?

### ISSUE THREAD

**Issue by Arthur2e5** [Nanolx/bashstyle-ng#3]
I am the translator Arthur200000 on Transifex. I found out that a lot of option names in NX-RC are translatable, but I don't think it looks like a good idea to translate them.

It's possible to add descriptions to the opt names in the native target language (so it looks like `extglob (拓展通配符)`), but I am not sure if it is a good idea.

**Comment by Arthur2e5** [comment]
That looks like unnecessary, since there are already descriptions in the UI.

**Comment by Nanolx** [comment]
You're right, it's better to leave the names intact. I'll change the scripts before releasing version 9.2

**Comment by Nanolx** [comment]
Fixed with commit 1a6bd5.
