### ISSUE TITLE
How do i set the destdir for ./make install

### ISSUE THREAD

**Issue by SolarAquarion** [Nanolx/bashstyle-ng#6]

**Comment by Nanolx** [comment]
By using the DESTDIR variable like DESTDIR=/test/ ./make install

Am 20. Dezember 2015 18:33:54 MEZ, schrieb SolarAquarion <notifications@github.com>:
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Nanolx/bashstyle-ng/issues/6

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by SolarAquarion** [comment]
bash: /usr/share/bashstyle-ng/rc/nx-rc: line 323: syntax error near unexpected token `('
bash: /usr/share/bashstyle-ng/rc/nx-rc: line 323: `reload () {'
bash: child setpgid (19642 to 19640): Operation not permitted

what about this

**Comment by Nanolx** [comment]
that's strange. Do you have any command in $PATH that's called 'reload'?

**Comment by SolarAquarion** [comment]
/usr/share/bashstyle-ng/rc/functions:./node_modules/.bin:/home/solaraquarion/.fzf/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/plan9/bin:/home/solaraquarion/.gem/ruby/2.2.0/bin:/home/solaraquarion/.config/bash/bash_it/plugins/available/todo
bash: child setpgid (31680 to 31678): Operation not permitted

**Comment by Nanolx** [comment]
No, I meant whether there's an executable of that name. Try: 'which reload'. You could also try prepending the word 'function' prior to reload in nx-rc.

Am 22. Dezember 2015 02:43:37 MEZ, schrieb SolarAquarion <notifications@github.com>:
>/usr/share/bashstyle-ng/rc/functions:./node_modules/.bin:/home/solaraquarion/.fzf/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/plan9/bin:/home/solaraquarion/.gem/ruby/2.2.0/bin:/home/solaraquarion/.config/bash/bash_it/plugins/available/todo
>bash: child setpgid (31680 to 31678): Operation not permitted
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Nanolx/bashstyle-ng/issues/6#issuecomment-166475459

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by SolarAquarion** [comment]
there's nothing for "reload"

**Comment by Nanolx** [comment]
what version of BashStyle-NG and Bash are you using, any other utilities for Bash like Bashish? What distro are you using?

**Comment by SolarAquarion** [comment]
I use Bash_it, bash version 4.3 and archlinux

**Comment by SolarAquarion** [comment]
>Bash Profile Aliases

>Bash it creates a reload alias that makes it convenient to reload your bash profile when you make changes.

**Comment by Nanolx** [comment]
Ok, a quick test with latest git head of BashStyle-NG and Bash_it seems fine, no more start-up issues.

But be aware that both may conflict in some regards, for example which one is loaded last sets the prompt. Though, I don't see any actual issues using both at the same time.

**Comment by SolarAquarion** [comment]
@Nanolx 

install stuff is doing odd things error: failed to commit transaction (conflicting files)
bashstyle-git: /usr/share/applications exists in filesystem
Errors occurred, no packages were upgraded.

**Comment by Nanolx** [comment]
This now, sorry, didn't test the latest changes when building the application using a package manager (successfully tested on Debian).
